movies = {
    "The Power of the Pup": ["6th December 2021", "Ceciline Bumberbach, Antonie Marie", "In the remote homestead in the Australian Outback, a newborn pup brings together a fractured family and touches everyone's hearts. Based on the original novel.", "https://www.rd.com/wp-content/uploads/2018/02/30_Adorable-Puppy-Pictures-that-Will-Make-You-Melt_124167640_YamabikaY.jpg", 4],
    "The Blobby": ["29th September 1956", "Jackie Newman, Geoffrey Rains", "A socially awkward blob person terrorises the people of a small american town in the 1960s, with hilarious results. A comedy remake of the Science-Terror film 'The Blob' from the 1930s.", "https://pbs.twimg.com/media/DM6SGToU8AAM5Bb?format=jpg&name=4096x4096", 3],
    "100 days of winter": ["14th April 1988", "Vivian Lowell, Jacqui Cork", "1889 in Central Europe, also known as \"The Year Without A Summer\". We follow the lives of a small farming family in Westphalia as they survive one of the coldest European Winters in modern times.", "https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/KHTBN7PKQRBV5EZAAC5Q6V2NXM.jfif&w=1440", 3],
    "Look After Her": ["3rd February 1970", "Peter Postwaiter, Shirley Smith", "In early 19th Century America, set against the Wild West and the movement of settlers into what would become Nevada, A young man makes a promise to his dying brother to care for his Widow and children as if they were his own.", "https://2.bp.blogspot.com/-yNXbQctlvJ4/VGCybcbbZFI/AAAAAAAAAO8/jm4MqrplTxQ/s1600/Diness-family-470x264.jpg", 4],
    "Hello Beef Wellington": ["7th June 1991", "Graham Morton, Arlene Tofar, Carianne Cathar", "An account of the first Trans-British Rally, driving from Scapa Flow at the northern tip of Scotland to Southhampton at the bottom of England.", "https://hips.hearstapps.com/amv-prod-gp.s3.amazonaws.com/gearpatrol/wp-content/uploads/2015/03/Erik-Carlsson-Gear-Patrol.jpg", 2],
    "The Sleepover": ["6th May 2002", "Shirley Smith, Geraldine Smith, Justin WoodWheat, Juanes Frescas", "On their last ever day of Secondary School, four teenagers have one last night together, facing their confusing futures as adults, old and new feelings about their coming lives and changing friendships, and the reveal of an unexpected secret.", "https://yourteenmag.com/wp-content/uploads/2018/06/sleepover-1135x540.jpg", 3],
    "The End of Time": ["3rd December 1999", "Ruth Ginzer, Jeffro Silvershadow", "James is relaxing at home, watching celebrations towards a new millenium count down. Unfortunately for him and the whole world, some bad computer code is about to cause the Apocalypse. Also features zombie republicans, vigilante grandmothers and a psychic dog. For reasons.", "https://i.guim.co.uk/img/media/674cbfe71db2ba5ff17151e999f7e6ad865159b0/0_58_1728_1037/master/1728.jpg?width=1200&height=900&quality=85&auto=format&fit=crop&s=509993097ffad8152a66a6d74d14e665", 4],
    "Children of the Mist": ["8th March 2008", "Vincent Vaughn, Ngaire Johnson", "A documentary of the Tuhoe Nation, from when europeans first arrived in the 1850s, to the treaty settlements and compensations of the 2010s.", "https://nzhistory.govt.nz/files/feb-29-1964-maungapohatu-road.jpg", 5],
}